WIP: Remove Trustzone root enclave
veracruz-project/veracruz pull request #205
Opened 2021-08-30 22:08 UTC by dreemkiller

2021-09-02 15:42 UTC, dominic-mulligan-arm commented
@dreemkiller could you register your GPG key with Github then sign the commit in this PR and force push?  Unfortunately, this process needs to be done for every PR that was opened before I turned signing on.

2021-09-20 18:41 UTC, dreemkiller commented
I have attempted to sign this one with GPG. Let me know how it goes...

2021-11-10 19:45 UTC, dreemkiller commented
This is ready to go in if someone wants to review it

2021-11-11 11:35 UTC, ShaleXIONG approved these changes

2021-11-11 13:17 UTC, dominic-mulligan-arm requested changes

2021-11-11 13:17 UTC, dominic-mulligan-arm commented on runtime-manager/Cargo.toml
> +libloading = "=0.5.2"
nit: can you move `libloading` above `uuid` to keep alphabetical order of imports after the recent formatting?

2021-11-11 13:17 UTC, dominic-mulligan-arm commented on test-collateral/generate-policy/Cargo.toml
> +veracruz-utils = {path = "../../veracruz-utils", features = ["std", "tz"]}
nit: can you move `veracruz-utils` down to retain alphabetical ordering of the imports?

2021-11-11 20:20 UTC, dominic-mulligan-arm approved these changes

2021-11-11 20:21 UTC, dominic-mulligan-arm commented
+1 reached, merging.

2021-11-11 20:21 UTC, merged