Add a facility similar to strace for showing WASI calls.
veracruz-project/veracruz pull request #308
Opened 2021-12-14 09:10 UTC by egrimley-arm

The command-line option is added and all WASI calls are instrumented,
but currently no output is generated as the corresponding functions
in strace.rs are just stubs, marked with "NOT YET IMPLEMENTED".

2021-12-16 15:20 UTC, ShaleXIONG approved these changes

2021-12-16 16:10 UTC, dominic-mulligan-arm requested changes

2021-12-16 16:10 UTC, dominic-mulligan-arm commented on execution-engine/src/lib.rs
> +    pub enable_strace: bool,
Can you put a `rustdoc`-style comment on this?

2021-12-16 16:13 UTC, dominic-mulligan-arm reviewed
(Other than that, this looks good to be merged.)

2021-12-17 09:23 UTC, dominic-mulligan-arm approved these changes

2021-12-17 09:23 UTC, dominic-mulligan-arm commented
+1 reached, merging.

2021-12-17 09:23 UTC, merged