Make changes required by changes in aws-nitro-enclaves-nsm-api.
veracruz-project/veracruz pull request #345
Opened 2022-02-24 21:33 UTC by egrimley-arm

They have reorganised the subcrates into modules.

Redirect to egrimley-arm to test while ring is not yet updated.

2022-02-24 22:04 UTC, dreemkiller requested changes
Wow! Quick work on this one.
There's about 35 places in `Cargo.toml`'s that need to be updated when https://github.com/veracruz-project/ring/pull/4 goes in (I've already approved it), or need to be reverted if we don't need changes for `rustls` or `webpki`.

2022-02-24 22:04 UTC, dreemkiller commented on session-manager/Cargo.toml
> +rustls = { git = "https://github.com/egrimley-arm/rustls.git", branch = "veracruz" }
Update this after the rustls PR goes in, or revert if there isn't one

2022-02-24 22:04 UTC, dreemkiller commented on veracruz-server-test/Cargo.toml
> +ring = { git = "https://github.com/egrimley-arm/ring.git", branch = "veracruz" }
Update this after https://github.com/veracruz-project/ring/pull/4 goes in

2022-02-24 22:51 UTC, mathias-arm commented
@dreemkiller I think what @egrimley-arm intended is to remove [533e469](https://github.com/veracruz-project/veracruz/pull/345/commits/533e469c05e006dce281dfc6bd8d5ea1ce6ca1d6) from the PR once https://github.com/veracruz-project/ring/pull/4 is merged.

This is another example of why #164 is needed. The equivalent to this PR on that branch is [9204430](https://github.com/veracruz-project/veracruz/pull/164/commits/92044308a2d0ac1c03527da0f11b1058384c895b).

2022-02-25 08:04 UTC, egrimley-arm commented
> This is another example of why #164 is needed. The equivalent to this PR on that branch is [9204430](https://github.com/veracruz-project/veracruz/pull/164/commits/92044308a2d0ac1c03527da0f11b1058384c895b).

Yes, I had to fork and modify the transitive closure of the repos that use `ring`. Some of that can be automated, with `perl -i`, but the actual forking requires browser interaction with GitHub.

2022-02-25 09:12 UTC, egrimley-arm commented
I've also removed a couple of version pinnings (`version = "=0.16.11"`). I had to remove them for testing, and they don't seem to be needed, so it didn't seem helpful to put them back!

2022-02-25 11:30 UTC, egrimley-arm commented on proxy-attestation-server/Cargo.toml
> +nitro-enclave-attestation-document = { git = "https://github.com/egrimley-arm/nitro-enclave-attestation-document.git", branch = "rename", optional = true }
No, it was only required by transitivity.

2022-02-25 11:33 UTC, egrimley-arm commented on session-manager/Cargo.toml
> +webpki = { git = "https://github.com/egrimley-arm/webpki.git", branch = "veracruz" }
No, it was just required by transitivity.

2022-02-25 11:34 UTC, egrimley-arm commented on veracruz-client/Cargo.toml
> +webpki = { git = "https://github.com/egrimley-arm/webpki.git", branch = "veracruz" }
I don't think so.

2022-02-25 12:36 UTC, gbryant-arm approved these changes

2022-02-25 12:39 UTC, merged