WIP: Experiment with replacing psa_crypto with mbedtls.
veracruz-project/veracruz pull request #501
Opened 2022-08-04 08:58 UTC by egrimley-arm

2022-08-04 21:45 UTC, egrimley-arm commented
The tests passed at https://github.com/veracruz-project/veracruz/actions/runs/2799377318

But I will try undoing some of the changes that perhaps were not necessary ...

2022-08-05 15:56 UTC, egrimley-arm commented
@gbryant-arm, it would be good if you could test this on Nitro, though I don't think this PR will help with the entropy problem you're currently working on.

@ShaleXIONG , it would be good if you could test the code in `aead.rs` and `aes.rs`.

2022-08-08 16:25 UTC, gbryant-arm requested changes
There still are references to `rust-psa-crypto` in some toml files under `workspace`

2022-08-11 11:11 UTC, gbryant-arm commented
`rust-mbedtls` doesn't get recompiled when making changes to `mbedtls_hardware_poll.c`:
I suggest we add the following code after https://github.com/veracruz-project/rust-mbedtls/blob/c9df29d0016de1d67ce597d6669e1ebda12dfb3d/mbedtls-sys/build/build.rs#L108:
```
// hardware poll                                                        
println!(                                                               
   "cargo:rerun-if-changed={}",                                        
   self.mbedtls_src                                                    
       .join(Path::new("..").join("build").join("mbedtls_hardware_poll.c"))
       .display()                                                      
); 
```

2022-08-11 11:32 UTC, gbryant-arm commented
Passes end to end with the tiny YOLO model :+1: 
It doesn't pass with the big model but that's orthogonal to this PR

2022-08-15 09:33 UTC, egrimley-arm commented
@gbryant-arm, I've fixed those two problems you pointed out and rebased.

2022-08-15 10:50 UTC, gbryant-arm approved these changes
Runs e2e on Nitro :heavy_check_mark:

2022-08-15 11:00 UTC, merged