Add $USER to all Docker image names.
veracruz-project/veracruz pull request #657
Opened 2023-08-17 12:43 UTC by egrimley-arm

This is another attempt to do what #650 was probably trying to do.

Based on #656.

2023-08-17 15:00 UTC, mathias-arm commented
I don't think we need the intermediate images to be renamed only the "leaf" one. I am worried also about the consequences on the `ci` image build.

2023-08-17 15:05 UTC, egrimley-arm commented
> I don't think we need the intermediate images to be renamed only the "leaf" one.

That might be what we already have (after #654 is applied).

> I am worried also about the consequences on the `ci` image build.

I'm worried about that, too, and generally how there a lot of things to test here.

2023-08-17 19:34 UTC, mathias-arm requested changes

2023-08-17 19:34 UTC, mathias-arm commented on third-party/rust-mbedtls
[9232612](https://github.com/veracruz-project/veracruz/pull/657/commits/92326124a717e700a3f1539b89c0aa927adaf813) includes this change which is surprising given the commit name. If I understand it changes from https://github.com/veracruz-project/rust-mbedtls/commit/7deda7121d54e97693c1e800bb717add116b80ef to https://github.com/veracruz-project/rust-mbedtls/commit/843291002b226a38821acda887bc05548dec2f2f which is to me a regression.

2023-08-17 20:38 UTC, egrimley-arm commented on third-party/rust-mbedtls
Oh, well spotted. It wouldn't be the first time that I've accidentally included a change to a submodule by changing to another branch, not doing `git submodule update`, and then using `git commit -a`.

2023-08-18 21:08 UTC, mathias-arm commented
Closing in favor of #656 which I think is the best solution.

2023-08-18 21:08 UTC, closed without merging