Renamed Mexico City to Runtime Manager
veracruz-project/veracruz pull request #94
Opened 2021-02-25 17:09 UTC by dominic-mulligan-arm

Documentation, comments, code, and build scripts.

2021-03-05 11:38 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 769ad300a60dac496a26c1ce585e23759f8178d8
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=34cf16fd-10a5-4aa9-89e3-18014a7a82c0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-05 16:24 UTC, ShaleXIONG commented on sinaloa/src/sinaloa_tz.rs
> +>>>>>>> a46d55a (mexico-city-renaming: further renaming of Mexico City)
I believe the top (HEAD) is what we want in term of this conflict.

2021-03-05 16:24 UTC, ShaleXIONG commented on sinaloa/src/sinaloa_tz.rs
> +>>>>>>> a46d55a (mexico-city-renaming: further renaming of Mexico City)
I believe the bottom (a46d55a) is what we want in term of this conflict.

2021-03-05 16:43 UTC, dominic-mulligan-arm commented
@ShaleXIONG, thanks, I missed those conflicts during a rebase earlier.

2021-03-05 17:24 UTC, ShaleXIONG approved these changes

2021-03-05 18:03 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 900a95d41d3081351342cc1f72186037bc8032fb
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=07b08b21-a80a-4a44-8d0d-86d19797be4a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-05 19:00 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 2a9d2b13707730f7aa6d4270ba31438a2ad95ea6
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=d341ef6a-b498-4d86-8702-b1b4e330d582%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-08 11:39 UTC, gbryant-arm approved these changes
LGTM

2021-03-08 14:07 UTC, ShaleXIONG submitted a review, later dismissed

2021-03-08 14:58 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: e11d90c741f94367747b3de0193acc71c2408557
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=249f7d78-e50e-492f-a68a-c8abe0459541%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-08 19:37 UTC, gbryant-arm requested changes
I don't know if you're done rebasing.
fwiw some symbols have not been renamed: "mc", "mc_nitro", "MCMessage", "mch_guard" (non exhaustive)

2021-03-09 09:32 UTC, dominic-mulligan-arm commented
> I don't know if you're done rebasing.
> fwiw some symbols have not been renamed: "mc", "mc_nitro", "MCMessage", "mch_guard" (non exhaustive)

Yeah, I seem to have messed up a recent rebase.

2021-03-09 10:42 UTC, gbryant-arm submitted a review, later dismissed
LGTM

2021-03-09 12:24 UTC, ShaleXIONG approved these changes

2021-03-09 12:24 UTC, ShaleXIONG commented on runtime-manager/Makefile
> +			# Makefile
There is an unexpected white space here. Not a big deal though.

2021-03-09 12:58 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: d8c9bb0211867c08e352641d8436321aaa0000cc
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=ad777849-9b8a-4a1b-93aa-d12056bdad08%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-09 12:59 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: a63dc294c1354f2f2e640dc7aeeb72b9404583c4
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=c3539cca-b1e5-4271-a549-c30a0f37d962%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-09 17:39 UTC, veracruz-project-owner commented
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 64d88c4f3386cba06800adda519057ac335054bb
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=235c44ce-8aab-4a33-9586-773010eb227b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-10 09:01 UTC, dominic-mulligan-arm commented
+1 reached, merging.

2021-03-10 09:01 UTC, merged